/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.yu_haruwolf.discord_tts_bot_with_voicevox;

import org.junit.jupiter.api.Test;

import com.github.yu_haruwolf.discord_tts_bot_with_voicevox.Bot;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Bot classUnderTest = new Bot();
    }
}
