/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.yu_haruwolf.discord_tts_bot_with_voicevox;

import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;

public class Bot {
    JDA jda;
    public static void main(String[] args) {
        new Bot();
    }

    Bot() {
        String token = System.getenv("TOKEN_DISCORD_TTS_BOT_WITH_VOICEVOX");
        jda = JDABuilder.createDefault(token).build();
    }
}
